### ISSUE TITLE
create issues using the OSS checklist

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#19]
Create issues in all open-source projects

> prerequisite completed: https://github.com/blindnet-io/openness-framework/pull/21
>
> followed by #9

**Comment by noelmace** [comment]
@filipblnt could you please add a comment listing the related issues you created? Thanks

**Comment by noelmace** [comment]
Sorry @filipblnt, but I can't see where. Here, I'm talking about the "checklist issues", not the projects. I'm just asking this to help us track this issue advancement and close it as soon as we're done.

**Comment by filipblnt** [comment]
Yes sorry. I was referring to that list of repositories, so **all** repositories listed there (which are actually the ones important for the dev offer) now have an issue titled "OSS checklist" containing the checklist already marked. I think it's easier to follow it at one place and modify it at one place if needed, otherwise it will be messy.

**Comment by noelmace** [comment]
Ok then, I'll update these issues' descriptions accordingly, close this one, and add the list to #9.
