### ISSUE TITLE
📌 Write a first basic tutorial

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#27]
## What?

Write a complete but simple tutorial explaining step-by-step how to set up and use the SDK in a basic but realistic web app.

## Why?

Help third-party developers better understand how the SDK can actually improve the development process "in real life".

## How?

Based on:
- blog posts by @milstan (TODO: add links)
- current documentation
- current "get started"

By the end of this task, the tutorial should be:
- available on blindnet.io (whatever what kind of dev portal we have at the time) with call-to-actions to make it visible and encourage its usage
- referenced in our repositories READMEs.

**Comment by noelmace** [comment]
Out of date. A more global update of the documentation is necessary. Other issues and epic will be created for that.

**Comment by Vuk-BN** [comment]
@noelmace just want to make sure we're on top of writing a first basic tutorial for our SDKs. 

I imagine this issue needs to be a part of [this](https://github.com/blindnet-io/blindnet.dev/issues/26#issuecomment-1191570419), no? 

I also imagine this tutorial being connected to the content we will put under '_Usage_' [here](https://github.com/blindnet-io/privacy-computation-engine), as well. 

In case I am mistake, let's discuss it tomorrow asap.

**Comment by noelmace** [comment]
This is not the issue you are looking for :wink: 
This one was about the previous SDKs, not the DevKit.
https://github.com/blindnet-io/product-management/issues/721#issuecomment-1196414662

**Comment by milstan** [comment]
@noelmace My understanding (maybe wrong) of what @Vuk-BN needs is:
- a "quick-start" type of tutorial (as of now while the system is being built) to be able to show it to potential clients and partners and aswer the question "how hard is this to integrate"

Ineed this issue was planned for SDK, not done, and then my understanding is:
- this issue changed scope by Filip's comment `But instead of just having a tutorial by looking at the current SDK only as it is now, I think it would be useful to look at the HLC/HLA and write that SDK tutorial in the context of HLC/HLA.` and mine too in May 2022, and thus remaind opened.
- to the best of my knoweldge there is no dedicated issue for such a tutorial in the context of devkit.

So if you are closing this issue, can you please make a new one, with aim to write this first basic tutorial in the context of devkit, and ideally responding to this need Vuk seems to be having, as described above.
