### ISSUE TITLE
📑 [Epic]: Transform Expected Behavior Document in easy-to-read How-Tos

### ISSUE THREAD

**Issue by milstan** [blindnet-io/devrel-management#50]
## Description

Automation of Privacy Request processing using [PRIV](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md) in blindnet devkit is currently specified in the [Expected Behavior](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/expected-behavior.md) document.

This document is suited for development purposes, but is not adapted for developers using blindnet devkit, because:
- it is not an easy read
- it is not modular - one must read the whole document to understand how things work
- It gets into too much detail about how things work

### Intended outcome

Several, well-targeted How-To documents.

## Sub-tasks

- [x] #51
- [x] #52

## Stakeholders

- @noelmace - make this happen
- @blindnet-io/engineering - contribute content to documents, as they develop components
- @milstan - contribute content and make sure everything is consistent

**Comment by noelmace** [comment]
I believe this goal is now met.

I'd still like to keep this in my backlog as a reminder to write a more thorough document on blindnet.dev based more specifically on [Expected Behavior](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/expected-behavior.md).

@milstan, if this sounds OK to you, we can move this issue to the Q4 milestone.

**Comment by milstan** [comment]
ok

**Comment by nweldev** [comment]
"writing a more thorough document on blindnet.dev based more specifically on [Expected Behavior](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/expected-behavior.md)" seems to have a low priority right now as it doesn't precisely feet in the current prioritization, so I'm closing this issue and will open a new one for this specifically in the future if necessary.
